### ISSUE TITLE
Tracking Gist parity

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#77]
Not all of these should be or need to be met, but I figure it may be helpful to see them listed here. Anything ~struck through~ is not currently being planned. 

- [ ] ability to specify spaces/tabs, indent size, and line wrapping behavior
- [ ] embeddable files
- [ ] ~post editing~ (you can make a copy, and I'm open to being able to edit descriptions so you can add a link)
- [ ] revision history view (as we have no git backing, we would just walk up the `parent` attribute that Posts have)
- [ ] search all users gists
